name: cjasm build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
#          - os: ubuntu-latest
#            buildname: 'ubuntu'
#            triplet: x64-linux
#            compiler: gcc_64
          - os: macos-latest
            buildname: 'macos / C++ tests'
            triplet: x64-osx
            compiler: clang_64

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake .
      - name: make
        run: make
      - name: test
        run: make test
